config/routes.rb
Rails.application.routes.draw do
  resources :system_informations
  get 'welcome/index'

  root 'welcome#index'

end

app/models/system_information.rb
class SystemInformation < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/system_informations_controller.rb
class SystemInformationsController < ApplicationController
  before_action :set_system_information, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :null_session

  # GET /system_informations
  # GET /system_informations.json
  def index
    @system_informations = SystemInformation.all
  end

  # GET /system_informations/1
  # GET /system_informations/1.json
  def show
  end

  # GET /system_informations/new
  def new
    @system_information = SystemInformation.new
  end

  # GET /system_informations/1/edit
  def edit
  end

  # POST /system_informations
  # POST /system_informations.json
  def create
    @system_information = SystemInformation.new(system_information_params)

    respond_to do |format|
      if @system_information.save
        format.html { redirect_to @system_information, notice: 'System information was successfully created.' }
        format.json { render :show, status: :created, location: @system_information }
      else
        format.html { render :new }
        format.json { render json: @system_information.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /system_informations/1
  # PATCH/PUT /system_informations/1.json
  def update
    respond_to do |format|
      if @system_information.update(system_information_params)
        format.html { redirect_to @system_information, notice: 'System information was successfully updated.' }
        format.json { render :show, status: :ok, location: @system_information }
      else
        format.html { render :edit }
        format.json { render json: @system_information.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /system_informations/1
  # DELETE /system_informations/1.json
  def destroy
    @system_information.destroy
    respond_to do |format|
      format.html { redirect_to system_informations_url, notice: 'System information was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_system_information
      @system_information = SystemInformation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def system_information_params
      params.require(:system_information).permit(:ram_available, :checked_at)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/system_informations_helper.rb
module SystemInformationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Empanadasonrails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/system_informations/_form.html.erb
<%= form_for(@system_information) do |f| %>
  <% if @system_information.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@system_information.errors.count, "error") %> prohibited this system_information from being saved:</h2>

      <ul>
      <% @system_information.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ram_available %><br>
    <%= f.number_field :ram_available %>
  </div>
  <div class="field">
    <%= f.label :checked_at %><br>
    <%= f.datetime_select :checked_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/system_informations/edit.html.erb
<h1>Editing System Information</h1>

<%= render 'form' %>

<%= link_to 'Show', @system_information %> |
<%= link_to 'Back', system_informations_path %>

app/views/system_informations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing System Informations</h1>

<table>
  <thead>
    <tr>
      <th>Ram available</th>
      <th>Checked at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @system_informations.each do |system_information| %>
      <tr>
        <td><%= system_information.ram_available %></td>
        <td><%= system_information.checked_at %></td>
        <td><%= link_to 'Show', system_information %></td>
        <td><%= link_to 'Edit', edit_system_information_path(system_information) %></td>
        <td><%= link_to 'Destroy', system_information, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New System information', new_system_information_path %>

app/views/system_informations/new.html.erb
<h1>New System Information</h1>

<%= render 'form' %>

<%= link_to 'Back', system_informations_path %>

app/views/system_informations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ram available:</strong>
  <%= @system_information.ram_available %>
</p>

<p>
  <strong>Checked at:</strong>
  <%= @system_information.checked_at %>
</p>

<%= link_to 'Edit', edit_system_information_path(@system_information) %> |
<%= link_to 'Back', system_informations_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
Empanadas on Rails!!!


Estamos en vivo!